// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (TbAlunos, error)
	DeleteAccount(ctx context.Context, idaluno int64) error
	GetAccount(ctx context.Context, idaluno int64) (TbAlunos, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]TbAlunos, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (TbAlunos, error)
}

var _ Querier = (*Queries)(nil)
